### ISSUE TITLE
License header in the code

### ISSUE THREAD

**Issue by kion-dgl** [andrewlowndes/image-packer#1]
Hi Andrew, I've been using your image packer as it's useful for doing the calculations of combining several images into a single texture. One problem I noticed is there doesn't seem to be a license header on your code, I made a sample which I appended to the code. I recommend adding it into your project.

```
/**
* image-packer
* A lightweight function that takes a set of dimensions and packs 
* them as best it can producing a list of positions
*
* Copyright (c) 2018 Andrew Lowndes
* https://github.com/andrewlowndes/image-packer        
* http://www.andrewlowndes.co.uk
*
* MIT license:
*   http://www.opensource.org/licenses/mit-license.php
**/
```

**Comment by andrewlowndes** [comment]
Many thanks for your suggestion Kion-dgl. I am not much of a fan of huge comment blocks, instead I have added a license file to the repository, which can be linked when using the library :)
